- name: Test basic connection and prerequisites
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Install minimal requirements for Ansible
      apt:
        name:
          - python3
          - python3-pip
          - sudo
        state: present
        update_cache: yes
        
    - name: Ensure packer user can sudo
      lineinfile:
        path: /etc/sudoers
        line: 'packer ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
        
    - name: Test simple command execution
      command: whoami
      register: whoami_result
      
    - name: Show whoami result
      debug:
        var: whoami_result.stdout
        
    - name: Test sudo access
      command: sudo whoami
      register: sudo_result
      
    - name: Show sudo result
      debug:
        var: sudo_result.stdout
